- id: cottage-status
  name: cottage-status
  description: check if the locally modified secrets are encrypted (fast, timestamp bases)
  entry: ctg status --skip-decryption --fail
  language: system
  pass_filenames: false
  always_run: true

- id: cottage-diff
  name: cottage-diff
  description: check with diff if the locally modified secrets are encrypted (slow, content based)
  entry: ctg diff --skip-decryption --fail
  language: system
  pass_filenames: false
  always_run: true

- id: cottage-encrypt
  name: cottage-encrypt
  description: encrypt the locally modified secrets (slow, content based)
  entry: ctg encrypt
  language: system
  pass_filenames: false
  always_run: true

- id: cottage-sync-decrypt
  name: cottage-sync-decrypt
  description: decrypt the upstream modified secrets (fast, timestamp based)
  entry: ctg sync --skip-encryption
  language: system
  stages: [post-checkout, post-merge]

- id: cottage-decrypt
  name: cottage-decrypt
  description: decrypt the upstream modified secrets (slow, content based)
  entry: ctg decrypt
  language: system
  stages: [post-checkout, post-merge]
