- id: cottage-status
  name: cottage-status
  description: check if the locally modified secrets are encrypted (timestamp bases)
  entry: ctg status --skip-decryption --fail
  language: system
  pass_filenames: false
  stages: [pre-commit, pre-push]
  always_run: true

- id: cottage-diff
  name: cottage-diff
  description: check with diff if the locally modified secrets are encrypted (timestamp based)
  entry: ctg diff --skip-decryption --fail
  language: system
  pass_filenames: false
  stages: [pre-commit, pre-push]
  always_run: true

- id: cottage-sync-encrypt
  name: cottage-sync-encrypt
  description: encrypt the locally modified secrets (timestamp based)
  entry: ctg sync --skip-decryption
  language: system
  pass_filenames: false
  stages: [pre-commit, pre-push]
  always_run: true

- id: cottage-encrypt
  name: cottage-encrypt
  description: encrypt the locally modified secrets (content based)
  entry: ctg encrypt
  language: system
  pass_filenames: false
  stages: [pre-commit, pre-push]
  always_run: true

- id: cottage-verify
  name: cottage-verify
  description: verify the upstream modified secrets (content based)
  entry: ctg verify
  language: system
  pass_filenames: false
  stages: [post-checkout, post-merge, post-rewrite]
  always_run: true

- id: cottage-sync-decrypt
  name: cottage-sync-decrypt
  description: decrypt the upstream modified secrets (timestamp based)
  entry: ctg sync --skip-encryption
  language: system
  pass_filenames: false
  stages: [post-checkout, post-merge, post-rewrite]
  always_run: true

- id: cottage-decrypt
  name: cottage-decrypt
  description: decrypt the upstream modified secrets (content based)
  entry: ctg decrypt
  language: system
  pass_filenames: false
  stages: [post-checkout, post-merge, post-rewrite]
  always_run: true
