[package]
name = "cottage"
version = "0.1.0"
edition = "2024"

[features]
default = ["complete"]
man = ["dep:clap_mangen"]
complete = ["dep:clap_complete"]

[dependencies]
age = { version = "0.11", features = ["armor", "ssh"] }
clap = { version = "4.6", features = ["derive"] }
anyhow = "1.0"
rpassword = "7.3"
walkdir = "2.5"
dirs = "6.0"
filetime = "0.2"
pathdiff = "0.2"
whoami = { version = "2.1", default-features = false, features = ["std"] }
blake3 = "1.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
hcl-rs = "0.19"
rust-ini = "0.21"
chrono = { version = "0.4", features = ["serde"] }
indexmap = { version = "2.14.0", features = ["serde"] }
similar = "3.1.0"
edit = "0.1.5"
owo-colors = "4.0.0"
dotenvy = "0.15.7"
clap-verbosity-flag = "3.0.4"
env_logger = "0.11.10"
log = "0.4.29"
toml = "1.1.2"
clap_mangen = { version = "0.3.0", optional = true }
clap_complete = { version = "4.6.3", optional = true }

[dev-dependencies]
assert_fs = "1.1.3"
