[package]
name = "cottage"
version = "0.6.3"
edition = "2024"
description = "A modern git based age-encrypted secrets manager for teams."
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sayanarijit/cottage"
authors = ["Arijit Basu <cottage@arijitbasu.in>"]
keywords = ["age", "git", "secrets", "cli", "command-line"]
categories = ["command-line-utilities", "filesystem", "development-tools"]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }-v{ version }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"
archive-suffix = "tar.gz"
pkg-fmt = "tgz"

[features]
default = ["autocomplete"]
autocomplete = ["dep:clap_complete"]

[dependencies]
age = { version = "0.11", features = ["armor", "ssh"] }
clap = { version = "4.6", features = ["derive", "env", "color"] }
anyhow = "1.0"
walkdir = "2.5"
dirs = "6.0"
filetime = "0.2"
pathdiff = "0.2"
whoami = { version = "2.1", default-features = false, features = ["std"] }
blake3 = "1.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
hcl-rs = "0.19"
rust-ini = "0.21"
chrono = { version = "0.4", features = ["serde"] }
indexmap = { version = "2.14.0", features = ["serde"] }
similar = "3.1.1"
edit = "0.1.5"
dotenvy = "0.15.7"
clap-verbosity-flag = "3.0.4"
env_logger = "0.11.10"
log = "0.4.30"
toml = "1.1.2"
clap_complete = { version = "4.6.5", optional = true }
colored = { version = "3.1.1" }
globset = { version = "0.4.18", features = [
  "serde1",
], default-features = false }
tempfile = "3.27.0"

[dev-dependencies]
assert_fs = "1.1.4"

[profile.release]
strip = true
codegen-units = 1
lto = true
panic = 'abort'
