[[repos]]
repo = "https://github.com/sayanarijit/cottage"
rev = "main"

# [pre|read] check if the locally modified secrets are encrypted (timestamp based)
[[repos.hooks]]
id = "cottage-status"

# [pre|read] check if the locally modified secrets are encrypted (timestamp based)
[[repos.hooks]]
id = "cottage-diff"

# [pre|write] encrypt the locally modified secrets (timestamp based)
[[repos.hooks]]
id = "cottage-sync-encrypt"

# [pre|write] encrypt the locally modified secrets (content based)
[[repos.hooks]]
id = "cottage-encrypt"

# [post|write] verify the upstream modified secrets (content based)
[[repos.hooks]]
id = "cottage-verify"

# [post|write] decrypt the upstream modified secrets (timestamp based)
[[repos.hooks]]
id = "cottage-sync-decrypt"

# [post|write] decrypt the upstream modified secrets (content based)
[[repos.hooks]]
id = "cottage-decrypt"
