[book]
title = "The cottage Book"
description = "cottage - A modern git based age-encrypted secrets manager for teams"
authors = ["Arijit Basu"]
language = "en"

[output.html]
git-repository-url = 'https://github.com/sayanarijit/cottage'
edit-url-template = 'https://github.com/sayanarijit/cottage/edit/main/docs/{path}'
default-theme = 'dark'
preferred-dark-theme = 'coal'
theme = "theme"

# [output.linkcheck]
# optional = true
