name: Cottage Verify
on: [push, pull_request]
permissions:
  contents: read
jobs:
  verify-secrets:
    runs-on: quay.io/sayanarijit/cottage:latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify secrets
        run: ctg verify
